// import type { Metadata } from 'next';
import { Lato, Comfortaa } from 'next/font/google';
import 'modern-normalize/modern-normalize.css';
import './globals.css';
import SideBar from '@/components/SideBar/SideBar';
import Header from '@/components/Header/Header';
import Breadcrumbs from '@/components/Breadcrumbs/Breadcrumbs';
import clsx from 'clsx';
import GreetingBlock from '@/components/GreetingBlock/GreetingBlock';

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
  variable: '--font-lato',
});

const comfortaa = Comfortaa({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-comfortaa',
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx('grid', lato.variable, comfortaa.variable)}>
        <SideBar />
        <div className="page ">
          <Header />
          <Breadcrumbs />
          <GreetingBlock/>
          {children}
        </div>
      </body>
    </html>
  );
}
